### ISSUE TITLE
Climate component problem

### ISSUE THREAD

**Issue by lmamakos** [BioSehnsucht/ha-elkm1#2]
I upgraded the elkm1 hass module from an earlier version, and noticed this issue.  I apologize in advance if this is already known:

```
2017-11-21 21:16:41 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/Users/louie/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 218, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/Users/louie/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/elkm1.py", line 111, in device_state_attributes
    ATTR_CURRENT_TEMPERATURE: self._convert_for_display(self._device.temp),
AttributeError: 'ElkClimateDevice' object has no attribute '_convert_for_display'

```

Sure enough, there's no `_covert_for_display` method defined in the elkm1 climate component.

I only started looking at this since it's getting cold outside and I thought, _"wouldn't it be nice to move the thermostat management out of the Elk into hass?"_    

I have an HAI "Omnistat" RC-80 thermostat connected to an Elk M1XSP adapto-module thing.  I'm sure the firmware in all of this is probably more than 4 years old at this point, but I'd be happy to try to do some further debugging if you can point me in the right direction.

**Comment by BioSehnsucht** [comment]
I think it might have been reported in the long thread on the HASS discussion site, if not something similar was.

Adding support for both C and F temp (previously was just F, as reported by Elk) is on the todo for next version. It's sort of halfway there. This should get fixed along with it.

Good news is someone generously sent me an Omnistat2 and M1XSP so I can actually test this properly now :D - before I just manufactured events and fed them into PyElk and this only tested if the theory was interpreted right, not if the theory was right :D

I was hoping to finally get the next release out this weekend but I forgot to factor in the holiday vacation with family so... probably another week.

**Comment by BioSehnsucht** [comment]
@lmamakos This should be fixed with latest update, I hope.

**Comment by lmamakos** [comment]
Great news, thanks!   I'm traveling now for a few days, I'll try the new version over the weekend and see how it goes.

**Comment by BioSehnsucht** [comment]
Based on your comments on the forum I'm going to close this as fixed in the new branch.
