### ISSUE TITLE
M1XEP reboot can go unnoticed until HASS tries to send message

### ISSUE THREAD

**Issue by BioSehnsucht** [BioSehnsucht/ha-elkm1#26]
Noticed this while testing #13 

When M1XEP reboots, the TCP connection dies on M1XEP's end naturally, but the other end may or may not notice the TCP connection is dead until HASS tries to send a message. Once this happens the reconnect logic works as expected, but can potentially be minutes or hours or more before this happens if you don't have any HASS automations constantly prodding the Elk.

Probably solution is to notice when M1XEP heartbeat 'XK' is missed 1 or more times and force reconnect? Per the protocol documentation, this is always sent even for serial connections, and doesn't have an option to turn it off, so it should be a reliable check. Though for serial connections there's not really any reconnecting to do, only really matters for TCP (secure and unsecure).

This could be implemented either in the `elkm1` library or in HASS code. 

@gwww thoughts?

**Comment by gwww** [comment]
New heartbeat code in elkm1-lib version 0.7.5. Ready to try.
