### ISSUE TITLE
Any way to get events from elkm1?

### ISSUE THREAD

**Issue by sjthespian** [BioSehnsucht/ha-elkm1#28]
I just received a call from my monitoring company that one of my wireless sensors has a low battery. Is there any way to receive event alerts via. the ElkM1 interface? It would be great to create an automation that could notify me of these before my alarm company calls.

Thanks!

**Comment by BioSehnsucht** [comment]
I think we might be able to detect this via either interpreting the system trouble status updates ('SS' messages, I believe @gwww has implemented storing them onto the panel sensor entity as an attribute - not sure if we're doing anything more yet such as applying them to individual entities?) or via the System Log Data update ('LD' messages - not yet implemented as far as I can tell). 

Probably the most straightforward way is to parse out any non-"Normal" status from 'SS' and update the appropriate entity somehow, then you could have automation triggers for any low battery or other trouble events.
